# See the syntax docs at
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Detect unused secrets
description: Detect unused github secrets

inputs:
  github-token:
    description: 'Github token'
    required: true

steps:
  - name: Access to repo content
  - uses: actions/checkout@v3

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'x'
  color: 'gray-dark'
